### ISSUE TITLE
Use Info Feed to show RSS feeds related to gaming news

### ISSUE THREAD

**Issue by sguergachi** [sguergachi/AuroraGameHub#17]
after the remake of infofeed is done this is a good place to start: http://www.vogella.com/articles/RSSFeed/article.html

modulerized it into a nice single class component to be placed in the engine, have it generate ArrayLists to be poured into the Info Feed in Aurora

InfoFeed should allow for a custom Font, custom Seperator image, custom Background image and custom Feed Items.

Linking should use this method: http://stackoverflow.com/questions/527719/how-to-add-hyperlink-in-jlabel

![infoFeed1](https://f.cloud.github.com/assets/615386/7396/cd2caafe-4407-11e2-9a34-788e14f97601.png)
![infoFeed2](https://f.cloud.github.com/assets/615386/7397/d1c98b2c-4407-11e2-99fc-4bd072fa44b8.png)

**Comment by camachado** [comment]
Info Feed fully implemented.
