### ISSUE TITLE
Current LICENSE.TXT restricts user freedoms

### ISSUE THREAD

**Issue by g4jc** [sguergachi/AuroraGameHub#43]
Hello,
This looks like a great project, however CC-BY-NC-ND means no one can even make derivatives for non-commercial use. I would suggest at minimum using CC-BY-NC-SA which allows derivatives for non commercial use that must be shared in the same license.

Alternatively consider a fully copyleft license:
https://www.gnu.org/licenses/license-list.html#which-cc
GPL or similar is also a good license.

Thanks and keep up the good work!

**Comment by sguergachi** [comment]
This is not the answer you are looking for but there are many particular reasons we have decided to stick with this particular license. If anyone wants to make a derivative we simply would like to know about it, we are more than willing to give permission and help anyone interested in creating a derivative of this project. We would just like to be  careful with the intentions.
