### ISSUE TITLE
A Rebranding and Refresh of the Default Surface

### ISSUE THREAD

**Issue by sguergachi** [sguergachi/AuroraGameHub#9]
Onix 2 Needs to be implemented

**Comment by sguergachi** [comment]
Preview Design of Cursor prototype:
![](http://f.cl.ly/items/2j270g2Z1k04252f3e3u/Cursor%20Design.png)

**Comment by camachado** [comment]
Can you make the selection cursor totally round? I'd like to see what it looks like compared to the one that you have right now.

**Comment by sguergachi** [comment]
Sure, I'll try that .

**Comment by sguergachi** [comment]
Some additional Select Cursor Style:

![](http://f.cl.ly/items/021Y1s36001Q2d3S1C2D/Cursor%20Designb.png)

**Comment by sguergachi** [comment]
Work In Progress, Best Viewed Full Screen.
![](https://dl.dropbox.com/u/1186703/Login_Window2.png)

**Comment by sguergachi** [comment]
Here are new Cursor Desings
![](https://dl.dropbox.com/u/1186703/Cursor%20Design.png)
![](https://dl.dropbox.com/u/1186703/Cursor%20Designb.png)

**Comment by sguergachi** [comment]
Dashboard UI W.I.P
![](https://dl.dropbox.com/u/1186703/Main_Menu.png)
